spring:
  application:
    name: inkflow-api
  datasource:
    url: jdbc:h2:mem:inkflow
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin